### ISSUE TITLE
Poder ejecutar los scripts desde cualquier carpeta

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wollok-cli#1]
No me queda claro si alcanzaría con agregar al repo al `PATH` o habría que hacer algo más. El uso me lo imagino así:

```bash
$ cd entregas/tp-golosinas-faloi
$ runTests.sh
```

**Comment by fdodino** [comment]
@faloi 

Acá una demo. Tenés que agregar al .bashrc (o al .profile) el PATH donde te descargaste wollok-cli (crearte un symlink con `ln` no va a funcionar porque tengo subcarpetas y es más complicado):

![wollokCli-runTests](https://user-images.githubusercontent.com/4549002/58324808-4be56200-7dfe-11e9-9a26-4d18448bfc0d.gif)

Pero todos los scripts ya funcionan con directorios relativos: generateCI, runTests, runPrograms y los w*.sh

**Comment by faloi** [comment]
¡De lujo! Cierro la issue entonces.

PD: si en el PR ponés "Closes #1" en vez de "Solving #1", se cierra solita la issue al mergear. También funciona con "Fixes" y algún otro que no recuerdo.

**Comment by fdodino** [comment]
Dale, yo estoy arreglando un tema que tengo que localmente me anda bien pero en Travis hay unos archivos para el sanity-check que me los está tomando y me rompe el build. Es temporal, pero te aviso.

**Comment by fdodino** [comment]
Listo, el build está arreglado. La única restricción es que no podés tener una carpeta en tu ejemplo que se llame `wsanity-check-examples`. Me parece que es poco probable que eso ocurra :smile:
