### ISSUE TITLE
Incorporar la versión de Wollok como badge

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-cli#10]

**Comment by fdodino** [comment]
Voy a descartarlo ya que automatizamos cada release de Wollok para que actualice wollok-cli

**Comment by npasserini** [comment]
No entendí este issue, ¿qué significa "badge"?
No sé si está exactamente relacionado pero me gustaría que los proyectos
wollok pasen a tener algo parecido a un "package.json" en el cual como
mínimo se especifique la versión de Wollok para la que fueron construidos.

**Comment by fdodino** [comment]
no, es otra cosa, quería que tuviéramos un badge de wollok-cli para avisar a qué versión de wollok estable estaba apuntando, pero ahora que están sincronizadas no vale la pena.
