### ISSUE TITLE
Fallan los builds que incluyen algo de game

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wollok-cli#12]
Se que es polémico, pero en una entrega de Game pedimos que hagan test, que en el Wollok IDE corren y luego en Travis no (en realidad sí corren, pero algo más falla). Se puede ver un ejemplo en https://travis-ci.com/faloi/defensa-tp-martes-GaianiMagali/builds/118119111.

La posta es que no sé cómo se llevan los tests con game, y ni siquiera estoy seguro de si deberían llevarse bien. El punto es que desacoplar `game` de los objetos de dominio está fuera del alcance de la materia, y a mí me gustaría que puedan convivir ambas cosas.

**Comment by PalumboN** [comment]
El error que tira es `java.lang.NoClassDefFoundError: org/uqbar/project/wollok/game/VisualComponent`
Puede ser que falten los jars de WollokGame o algo así? Recuerdo que Fer había seleccionado los archivos mínimos necesarios para el cli.

A mi también me gustaría tener el CI para los proyectos con Game :)

**Comment by faloi** [comment]
No está relacionado pero pregunto: ¿el estado del `game` se reinicia entre
cada test?

No lo probé intensivamente, pero me animo a decir que no.

**Comment by fdodino** [comment]
Habría que buscar el jar de Wollok Game e incorporarlo, es raro.

El estado de game debería reiniciarse como todo wko entre cada test...

**Comment by fdodino** [comment]
Ya encontré que falta copiar el jar `wollok.game`, lo voy a incluir a mano y lo incorporo al script

**Comment by fdodino** [comment]
@faloi podrías probar ahora?

Corrí un build de pepitaGame y anduvo, pero no tiene tests, los programas rompen obviamente porque no tenemos Open GL y además porque no se pueden correr batch (no tiene sentido). Pero ya incorporé wollok.game dentro de los jars a copiar, y también los jars propios de la carpeta `lib`

**Comment by npasserini** [comment]
Si ya lo tenemos andando démosle para adelante, pero en realidad lo ideal
sería tener un mock de game para los tests, ¿qué les parece?

**Comment by fdodino** [comment]
Cierro el issue original, lo de los mock para game me parece excelente, carguemos un issue en wollok-xtext...
