### ISSUE TITLE
Al correr todos los tests de un proyecto levanta una vm por cada test

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok-cli#16]
Esto lo hace muy lento, deberíamos correr todos los tests en una única VM. Para correr los sanity tests tarda varios minutos. Además el informe de errores quedaría más útil si podemos armar un único árbol en lugar de un montón.

**Comment by npasserini** [comment]
En realidad levanta una VM por archivo.

**Comment by fdodino** [comment]
Reabro hasta que se arregle `-severalFiles`, está en el archivo `commons.sh` el código que va (pero comentado)
