### ISSUE TITLE
Build de Travis exitoso cuando hay errores

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok-cli#20]
Tengo un build en passing a pesar de que hay errores al correr los tests. Lo acabo de restartear para ver si el resultado erróneo se mantenía, y sí. Dejo algunos screenshots:

![imagen](https://user-images.githubusercontent.com/715971/65150358-56a1b380-d9fa-11e9-82b1-bd3548f9e6e0.png)

![imagen](https://user-images.githubusercontent.com/715971/65150367-5c979480-d9fa-11e9-8111-43cf9dbaa7ab.png)

Por otro lado, habían dos archivos de test más que no se están teniendo en cuenta en el build directamente y no sé por qué (en los proyectos de los otros alumnos sí se están teniendo en cuenta y ni siquiera habían cambios sobre esos archivos en el repo en base a lo que les dimos).

Así se ve la corrida a nivel proyecto desde el IDE:
![imagen](https://user-images.githubusercontent.com/715971/65150401-71742800-d9fa-11e9-9f0d-7d49a12cb6f6.png)

Si alguien quiere acceso al repo de ese TP para ver más detalles, avisen y los agrego como colaboradores.

**Comment by fdodino** [comment]
Con la versión de wollok-cli anterior a este fin de semana funciona ok, voy a investigar qué pudo cambiar.

**Comment by fdodino** [comment]
Cierro el issue (me olvidé de referenciarlo): 7029ac72f9fb617cfa3f93ebabac993cc1496ae7 fue el commit que lo arregla, provisoriamente volvemos a interpretar de a un solo archivo
