### ISSUE TITLE
Build de travis exitoso cuando hay errores de compilación

### ISSUE THREAD

**Issue by JuanFdS** [uqbar-project/wollok-cli#24]
Aunque hayan tests que fallan, parece que ante ciertos errores al tratar de ejecutar la suite de tests, el comando `wollok test` da un exit code de 0, y esto hace que pase travis por ej..

Una forma de reproducirlo es, dentro de un describe pero fuera de test, tratar de instanciar una clase asignando un atributo a si mismo.

![image](https://user-images.githubusercontent.com/11432672/67826069-137f3980-faaa-11e9-8d06-a0b59be42af9.png)

Acá hay un repo que se puede clonar para probar ese caso que mencione arriba:
https://github.com/JuanFdS/wollok-cli-bug-report

**Comment by fdodino** [comment]
Gracias @JuanFdS !

El error es de Wollok Xtext, cuando se rompe la inicialización del describe también el IDE se rompe con un error:NULL. Yo ya reporté el error y lo corregí pero no está en producción. Podés probar apuntando Wollok a dev en lugar de stable.

**Comment by fdodino** [comment]
Acá está el issue original: https://github.com/uqbar-project/wollok/issues/1841

Una vez que hagamos el release todo debería ir bien.

**Comment by fdodino** [comment]
Cierro el issue - se arregló con el último release
