### ISSUE TITLE
Problema al instalar los script

### ISSUE THREAD

**Issue by alexistdk** [uqbar-project/wollok-cli#29]
Buenas,

Estoy teniendo algún problema con la instalación de los script. Seguí las instrucciones y puse el 
`export PATH="$PATH:<<pathWhereThisRepoWasCloned>>"` tanto en los archivos `/etc/profile` y `/.bashrc `¿qué estoy haciendo mal?

**Comment by fdodino** [comment]
Mmm... Tenés que poner el directorio dónde clonaste wollok-cli, no uses literalmente la carpeta pathWhereThisRepoWasCloned porque no va a existir.

**Comment by alexistdk** [comment]
Lo sé, el repo lo tengo clonado en /home/alexis/wollok-cli y cambié el <<pathWhereThisRepoWasCloned>> por dicha dirección. Quizá debería haberme expresado mejor. En fin, al poner `export PATH="$PATH:/home/alexis/wollok-cli` en dichos archivos no pasa nada

**Comment by fdodino** [comment]
Ok. De curioso, dónde estás cursando Alexis? 
Ahora sí, las preguntas:
1) ¿Qué significa que no pasa nada?
2) ¿Qué sistema operativo es? ¿Qué versión de bash estás usando?
3) ¿Tenés instalado Java 8? ¿JRE o JDK?
4) Y no entiendo que no pasa nada, yo esperaría un mensaje de error "wollok: not found" o algo así.

```bash
wollok repl
```

Debería funcionar.

**Comment by alexistdk** [comment]
> dónde estás cursando Alexis?

Los sábados a la tarde con Gastón en la UTN

> ¿Qué significa que no pasa nada?

Justamente devuelve un wollok: not found, pero me refería a que no hace lo que esperaba

> ¿Qué sistema operativo es? ¿Qué versión de bash estás usando?

Estoy usando Manjaro 20.1 Mikah y la versión de bash es 5.0.18(1)-release

> ¿Tenés instalado Java 8? ¿JRE o JDK?

La versión 11 del JDK que es la que está en los repos oficiales de Manjaro. 

Cabe aclarar que el IDE de Wollok funciona, pero me siento más cómodo con la terminal y de ahí el querer instalarlo


Edit: ahí pude hacerlo andar, disculpá las molestias. ya podes cerrar el issue

**Comment by fdodino** [comment]
Ok, entonces hay que probar algunas cosas:

1) Fijate si yendo al directorio donde lo instalaste y hacés

```bash
$ ./wollok repl
```

eso levanta la consola.

2) Lo mismo pero sin `./`:

```bash
$ wollok repl
```

3) Veamos qué dice tu PATH:

```bash
$ env | grep PATH
```

4) Y antes de pasame los archivos /etc/profile y .bashrc, fijate [este issue de Manjaro](https://nanxiao.me/en/why-doesnt-profile-take-effect-in-arch-linux/). Lo más probable es que uno de tus archivos de profile pise al otro.

**Comment by fdodino** [comment]
Cierro el issue @alexistdk , si persiste avisanos y lo abrimos.
