### ISSUE TITLE
Poder correr un REPL sin ningún archivo

### ISSUE THREAD

**Issue by faloi** [uqbar-project/wollok-cli#5]
Análogo al REPL vacío que existe en el wollok-ide.

**Comment by fdodino** [comment]
Lo loco es que si le tiro `wrepl.sh` me levanta ok.
Pero no si hago `wollok repl`

**Comment by fdodino** [comment]
![wollokCli-repl-withoutFile](https://user-images.githubusercontent.com/4549002/58369589-ec0cbb00-7ed2-11e9-8d79-4793b2d0501b.gif)

Estoy haciéndole algunos arreglitos adicionales, los subo en ese PR.
